/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.pi.gui;

import br.edu.utfpr.cm.pi.conexao.Data;
import br.edu.utfpr.cm.pi.conexao.TransactionManager;
import br.edu.utfpr.cm.pi.daos.DaoOrdemCompra;
import br.edu.utfpr.cm.pi.daos.DaoOrdemVenda;
import br.edu.utfpr.cm.pi.entidades.Fornecedor;
import br.edu.utfpr.cm.pi.entidades.OrdemCompra;
import br.edu.utfpr.cm.pi.entidades.Produto;
import br.edu.utfpr.cm.pi.util.Util;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TAYLY
 */
public class JDialogOrdemDeCompra extends javax.swing.JDialog {

    /**
     * Creates new form JDialogOrdemDeCompra
     */
    private Fornecedor fornecedor;
    private Calendar data;
    private List<Produto> produtos;
    
    public JDialogOrdemDeCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        pegarData();
        produtos = new ArrayList();
        carregarTabelaProdutos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparatorCadForn = new javax.swing.JSeparator();
        jLabelCadFornCodigo = new javax.swing.JLabel();
        jTextFieldCodigoOrdem = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelCadFornNome = new javax.swing.JLabel();
        jTextFieldFornecedor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonApagar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jFormattedTextFieldDataCompra = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldValorTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Ordem de Compra");

        jSeparatorCadForn.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jSeparatorCadForn.setMaximumSize(new java.awt.Dimension(750, 5));
        jSeparatorCadForn.setMinimumSize(new java.awt.Dimension(750, 5));
        jSeparatorCadForn.setPreferredSize(new java.awt.Dimension(740, 5));

        jLabelCadFornCodigo.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadFornCodigo.setText("Código:");

        jTextFieldCodigoOrdem.setEditable(false);
        jTextFieldCodigoOrdem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jButtonPesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/DocumentIconAd.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setPreferredSize(new java.awt.Dimension(24, 24));
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jLabelCadFornNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelCadFornNome.setText("Fornecedor:");

        jTextFieldFornecedor.setEditable(false);
        jTextFieldFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/Close_.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableProdutos);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Bebidas");

        jButtonSalvar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/save01.png"))); // NOI18N
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonApagar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonApagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/trash.png"))); // NOI18N
        jButtonApagar.setToolTipText("Apagar");
        jButtonApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarActionPerformed(evt);
            }
        });

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Data:");

        try {
            jFormattedTextFieldDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/add_1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/pi/icons/add_1.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Valor total R$:");

        jTextFieldValorTotal.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButtonSalvar)
                .addGap(5, 5, 5)
                .addComponent(jButtonLimpar)
                .addGap(5, 5, 5)
                .addComponent(jButtonApagar)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jButtonFechar)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1))
                    .addComponent(jSeparatorCadForn, javax.swing.GroupLayout.PREFERRED_SIZE, 702, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabelCadFornCodigo)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldCodigoOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(jFormattedTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabelCadFornNome)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jSeparatorCadForn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabelCadFornCodigo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTextFieldCodigoOrdem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jFormattedTextFieldDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabelCadFornNome))
                    .addComponent(jTextFieldFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonLimpar)
                    .addComponent(jButtonApagar)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        abrirJanelaPesquisaOrdemDeCompra();
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        cadastrarOrdemCompra();
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        // TODO add your handling code here:
        limparFormulario();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarActionPerformed

        // TODO add your handling code here:
        deletarOrdemCompra();
    }//GEN-LAST:event_jButtonApagarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        if (Util.imprimirConfirmacao("Deseja Sair?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        buscarFornecedor();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        buscarProduto();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        apagarProdutoDaLista();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogOrdemDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogOrdemDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogOrdemDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogOrdemDeCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogOrdemDeCompra dialog = new JDialogOrdemDeCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonApagar;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataCompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCadFornCodigo;
    private javax.swing.JLabel jLabelCadFornNome;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparatorCadForn;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldCodigoOrdem;
    private javax.swing.JTextField jTextFieldFornecedor;
    private javax.swing.JTextField jTextFieldValorTotal;
    // End of variables declaration//GEN-END:variables

    private void abrirJanelaPesquisaOrdemDeCompra() {
        Util.abrirJDialogCentralizado(new JDialogPesquisarOrdemCompra(null, true));
        OrdemCompra ordem = (OrdemCompra) Data.hash.get("ordemCompra");
        if (ordem == null) {
            return;
        }
        Data.hash.remove("ordemCompra");
        preencherFormularioComDados(ordem);
    }

    private void cadastrarOrdemCompra() {
        if (validarCampos()) {
            OrdemCompra ordem = new OrdemCompra();

            if (new Util().validarID(jTextFieldCodigoOrdem.getText())) {
                ordem.setId(Integer.parseInt(jTextFieldCodigoOrdem.getText()));
                ordem.setDataCompra(data);
                ordem.setFornecedor(fornecedor);
                ordem.setProdutos(produtos);


            } else {
                ordem.setDataCompra(data);
                ordem.setFornecedor(fornecedor);
                ordem.setProdutos(produtos); 
            }


            try {
                TransactionManager.beginTransaction();
                DaoOrdemCompra dGP = new DaoOrdemCompra();

                dGP.persist(ordem);
                TransactionManager.commit();
                JOptionPane.showMessageDialog(rootPane, "Cadastrado com sucesso!");
                limparFormulario();
            } catch (Exception e) {
                TransactionManager.rollback();
                JOptionPane.showMessageDialog(rootPane, "A ordem de compra não pode ser cadastrada" + e);
                System.out.println(e);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Verifique os erros antes de continuar!");
        }
    }

    private void limparFormulario() {
        fornecedor = new Fornecedor();
        produtos = new ArrayList();
        jTextFieldCodigoOrdem.setText(null);
        jTextFieldFornecedor.setText(null);
        jTextFieldFornecedor.setBackground(Color.white);
        carregarTabelaProdutos();
        jFormattedTextFieldDataCompra.setText(null);
    }

    private void deletarOrdemCompra() {
        if (new Util().validarID(jTextFieldCodigoOrdem.getText())) {
            try {
                TransactionManager.beginTransaction();
                Integer id = Integer.parseInt(jTextFieldCodigoOrdem.getText());
                DaoOrdemCompra dE = new DaoOrdemCompra();
                OrdemCompra ordem = dE.retrive(id);
                dE.delete(ordem);
                TransactionManager.commit();
                limparFormulario();
                JOptionPane.showMessageDialog(rootPane, "Excluido com sucesso!");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Erro ao excluir!");
                TransactionManager.rollback();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um item para excluir!");
        }
    }

    private void buscarFornecedor() {
        Util.abrirJDialogCentralizado(new JDialogPesquisarFornecedor(null, true));
        fornecedor = (Fornecedor) Data.hash.get("fornecedor");
        if (fornecedor == null) {
            return;
        }
        Data.hash.remove("fornecedor");
        jTextFieldFornecedor.setText(fornecedor.getRazaoSocial());
    }

    private void pegarData() {
        data = Calendar.getInstance();
        jFormattedTextFieldDataCompra.setText(new Util().calendarToString(data));
    }

    private void buscarProduto() {
        Util.abrirJDialogCentralizado(new JDialogPesquisarProduto(null, true));
        Produto produto = (Produto) Data.hash.get("produto");
        if (produto == null) {
            return;
        }
        Data.hash.remove("produto");
        produtos.add(produto);
        carregarTabelaProdutos();
    }

    private void carregarTabelaProdutos() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new String[]{"Código", "Nome", "Valor", "Quantidade", "Grupo"});

        if (produtos != null) {
            for (Produto produto : produtos) {
                model.addRow(new Object[]{produto.getId(), produto.getNome(), produto.getValor(), produto.getQuantidade(), produto.getGrupoDeProduto().getDescricao()});
            }
            jTableProdutos.setModel(model);
            calcularvalorTotalProdutos(produtos);
        }
        

    }

    private boolean validarCampos() {
        int erros = 0;
        if (jTextFieldFornecedor.getText() == null || jTextFieldFornecedor.getText().equals("")) {
            jTextFieldFornecedor.setBackground(new Color(247, 169, 157));
            erros++;
        }
        if (produtos == null || produtos.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Insira pelo menos 1 produto!");
            erros++;
        }
        if(new Util().stringToCalendar(jFormattedTextFieldDataCompra.getText()) == null){
             jFormattedTextFieldDataCompra.setBackground(new Color(247, 169, 157));
            erros++;
        }
        
        if (erros != 0) {
            return false;
        }
        return true;
    }

    private void preencherFormularioComDados(OrdemCompra ordem) {
        fornecedor = ordem.getFornecedor();
        data = ordem.getDataCompra();
        produtos = ordem.getProdutos();
        
        jTextFieldCodigoOrdem.setText(String.valueOf(ordem.getId()));
        jTextFieldFornecedor.setText(ordem.getFornecedor().getRazaoSocial());
        carregarTabelaProdutos();
        jFormattedTextFieldDataCompra.setText(new Util().calendarToString(data));
        
    }

    private void calcularvalorTotalProdutos(List<Produto> produtos) {
        double valorTotal = 0.0;
        for (int i = 0; i < produtos.size(); i++) {
            
            valorTotal+= (produtos.get(i).getQuantidade()*produtos.get(i).getValor());
        }
        jTextFieldValorTotal.setText(String.valueOf(valorTotal));
    }

    private void apagarProdutoDaLista() {
        int linha = jTableProdutos.getSelectedRow();
        if(linha != -1){
            produtos.remove(linha);
            carregarTabelaProdutos();
        }
    }
}
