/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.cm.tsi.gui;

import br.edu.utfpr.cm.pi.util.Util;


/**
 *
 * @author TAYLY
 */
public class JDialogPesquisarFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDialogPesquisarFornecedor
     */
    public JDialogPesquisarFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jLabelpesClienteImagem = new javax.swing.JLabel();
        jTextFieldPesFornCod = new javax.swing.JTextField();
        jLabelPesClienteCod = new javax.swing.JLabel();
        jLabelPesClienteCPF = new javax.swing.JLabel();
        jLabel1PesFornCodNome = new javax.swing.JLabel();
        jTextFieldpesPesFornCod = new javax.swing.JTextField();
        jFormattedTextFieldPesFornCod = new javax.swing.JFormattedTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePesquisarCliente = new javax.swing.JTable();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonCadFornecedor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        setMinimumSize(new java.awt.Dimension(620, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelpesClienteImagem.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelpesClienteImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelpesClienteImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/name/PesquisarFornecedor.png"))); // NOI18N
        getContentPane().add(jLabelpesClienteImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 280, 50));

        jTextFieldPesFornCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(jTextFieldPesFornCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 110, -1));

        jLabelPesClienteCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPesClienteCod.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelPesClienteCod.setText("Código:");
        getContentPane().add(jLabelPesClienteCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabelPesClienteCPF.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelPesClienteCPF.setText("CPF:");
        getContentPane().add(jLabelPesClienteCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel1PesFornCodNome.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1PesFornCodNome.setText("Nome:");
        jLabel1PesFornCodNome.setToolTipText("");
        getContentPane().add(jLabel1PesFornCodNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jTextFieldpesPesFornCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldpesPesFornCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(jTextFieldpesPesFornCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 230, -1));

        try {
            jFormattedTextFieldPesFornCod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldPesFornCod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jFormattedTextFieldPesFornCod.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        getContentPane().add(jFormattedTextFieldPesFornCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 110, -1));

        jButtonPesquisar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/icons/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setToolTipText("Pesquisar");
        jButtonPesquisar.setMaximumSize(new java.awt.Dimension(72, 72));
        jButtonPesquisar.setMinimumSize(new java.awt.Dimension(72, 72));
        jButtonPesquisar.setPreferredSize(new java.awt.Dimension(72, 72));
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 50, 50));

        jTablePesquisarCliente.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTablePesquisarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Cod", "Nome", "Logradouro", "Numero", "Estado", "Municipio", "Bairro", "Telefone", "E-mail"
            }
        ));
        jScrollPane1.setViewportView(jTablePesquisarCliente);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 540, 160));

        jButtonAtualizar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/icons/update.png"))); // NOI18N
        jButtonAtualizar.setToolTipText("Atualizar");
        getContentPane().add(jButtonAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, -1, -1));

        jButtonLimpar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/icons/clear02.png"))); // NOI18N
        jButtonLimpar.setToolTipText("Limpar");
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, -1, -1));

        jButtonFechar.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/icons/Close.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 390, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(620, 1));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 620, 1));

        jButtonCadFornecedor.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCadFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/cm/tsi/icons/Forn.png"))); // NOI18N
        jButtonCadFornecedor.setToolTipText("Cadastrar Fornecedor");
        getContentPane().add(jButtonCadFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, -1, -1));

        setSize(new java.awt.Dimension(636, 519));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
      if (Util.imprimirConfirmacao("Deseja Sair?")) {
            dispose();
        }
    }//GEN-LAST:event_jButtonFecharActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogPesquisarFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogPesquisarFornecedor dialog = new JDialogPesquisarFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCadFornecedor;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JFormattedTextField jFormattedTextFieldPesFornCod;
    private javax.swing.JLabel jLabel1PesFornCodNome;
    private javax.swing.JLabel jLabelPesClienteCPF;
    private javax.swing.JLabel jLabelPesClienteCod;
    private javax.swing.JLabel jLabelpesClienteImagem;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTablePesquisarCliente;
    private javax.swing.JTextField jTextFieldPesFornCod;
    private javax.swing.JTextField jTextFieldpesPesFornCod;
    // End of variables declaration//GEN-END:variables
}
